//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MyGrammer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMyGrammerListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MyGrammerBaseListener : IMyGrammerListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] MyGrammerParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] MyGrammerParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.declarlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarlist([NotNull] MyGrammerParser.DeclarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.declarlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarlist([NotNull] MyGrammerParser.DeclarlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] MyGrammerParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] MyGrammerParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] MyGrammerParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] MyGrammerParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.elseifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseifStatement([NotNull] MyGrammerParser.ElseifStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.elseifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseifStatement([NotNull] MyGrammerParser.ElseifStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] MyGrammerParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] MyGrammerParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.declar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclar([NotNull] MyGrammerParser.DeclarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.declar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclar([NotNull] MyGrammerParser.DeclarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.declar2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclar2([NotNull] MyGrammerParser.Declar2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.declar2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclar2([NotNull] MyGrammerParser.Declar2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.firstPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFirstPart([NotNull] MyGrammerParser.FirstPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.firstPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFirstPart([NotNull] MyGrammerParser.FirstPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.lastPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLastPart([NotNull] MyGrammerParser.LastPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.lastPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLastPart([NotNull] MyGrammerParser.LastPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] MyGrammerParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] MyGrammerParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] MyGrammerParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] MyGrammerParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.prints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrints([NotNull] MyGrammerParser.PrintsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.prints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrints([NotNull] MyGrammerParser.PrintsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] MyGrammerParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] MyGrammerParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] MyGrammerParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] MyGrammerParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyGrammerParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] MyGrammerParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyGrammerParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] MyGrammerParser.FactorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
